### ISSUE TITLE
opengl.h _stdcall error

### ISSUE THREAD

**Issue by Giacom** [nlguillemot/dof#1]
Hi, I am teaching myself OpenGL using your [opengl.h](opengl.h) as a loader. It works great, thanks for it and for the article though I noticed that when I tried to get it running on Windows 10, after developing my simple example app on Linux, that it would not compile as it had macro related errors.

I managed to fix it by changing `_stdcall` to `__stdcall` in the opengl.h file.

I find it weird because you are developing on Windows too, maybe it is because I am using Mingw32 instead of MSVC. I am not sure.

Anyway this is what I changed to fix it.

```C++
#ifndef GLAPIENTRY
#ifdef _WIN32
#define GLAPIENTRY __stdcall // was _stdcall
#else
#define GLAPIENTRY
#endif
#endi
```

I thought I would let you know so that it may be solved here, if you want, in order to prevent anyone else from receiving the same problem.

Thanks, Alex.

**Comment by nlguillemot** [comment]
Nice catch, thanks for sharing! Seems `_stdcall` is a MSVC thing. The double underscore works too, so I updated opengl.h with it to be compatible with MinGW.

That said, if you're learning OpenGL, I would recommend using MSVC instead. 🙂 It has a much better C++ debugger, and Visual Studio has NVIDIA NSight integration (to use NVIDIA's OpenGL debugger).
Just my opinion, and I can understand why you're using MinGW if you're also working on Linux.

Thanks again for sharing!

**Comment by Giacom** [comment]
Cool and yeah I definitely have to check out NSight, it looks super useful. Thanks.

**Comment by nlguillemot** [comment]
NSight has definitely saved me a lot of development time. Definitely definitely look at RenderDoc too, it's a life saver.
